services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: langame
      MYSQL_USER: langame
      MYSQL_PASSWORD: changemetoo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: